# Meson cross file for targeting Windows from Linux
# This is the MATLAB-specific cross file, to be included before the common cross file

[project options]
build_for='matlab'

[constants]
slicot_path='/tmp/windeps/sysroot-matlab/mingw64/lib'

[properties]
sys_root='/tmp/windeps/sysroot-matlab/'
pkg_config_libdir = '/tmp/windeps/sysroot-matlab/mingw64/lib/pkgconfig'
boost_root = '/tmp/windeps/sysroot-matlab/mingw64'
