# Meson common cross file for targeting Windows from Linux
# To be included after mingw-cross-{matlab,octave}.ini

[constants]
# For the architectural baseline, we follow MSYS2:
# https://www.msys2.org/news/#2022-10-18-new-minimum-hardware-requirements-cpus-from-20067
# If this is modified, windows/deps/toolchain-mingw64.cmake should also be updated
arch_flags = [ '-march=nocona', '-msahf', '-mtune=generic' ]

[binaries]
cpp = 'x86_64-w64-mingw32ucrt-g++'
fortran = 'x86_64-w64-mingw32ucrt-gfortran'
c = 'x86_64-w64-mingw32ucrt-gcc'
strip = 'x86_64-w64-mingw32ucrt-strip'
ar = 'x86_64-w64-mingw32ucrt-gcc-ar'
pkg-config = 'x86_64-w64-mingw32ucrt-pkg-config'

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[project options]
pardiso = 'enabled'
suitesparse_src_path = '/tmp/windeps/src/suitesparse'

[built-in options]
prefer_static = true

cpp_args = arch_flags
fortran_args = arch_flags + [ '-B', slicot_path ]
c_args = arch_flags
