list_of_functions = {'discretionary_policy_1', 'dyn_first_order_solver',...
                    'evaluate_likelihood', ...
                    '+identification/analysis.m', ...
                    'masterParallel', ...
                    '+pruned_SS.pruned_state_space_system','+pruned_SS.allVL1',...
                    '+wait_bar.multi',...
                    'gensylv_fp','lyapunov_symm',...
                    '+occbin/solver.m','+occbin/mkdatap_anticipated_dyn.m','+occbin/mkdatap_anticipated_2constraints_dyn.m','+occbin/match_function.m','+occbin/solve_one_constraint.m','+occbin/solve_two_constraint.m','+occbin/plot/shock_decomposition.m'};
